spring.application.name=kanban


#Database Connection
spring.datasource.url = jdbc:mysql://bgp7k2vqt4txkxf9vmyp-mysql.services.clever-cloud.com:3306/bgp7k2vqt4txkxf9vmyp
spring.datasource.username = ucziednt4iehswbv
spring.datasource.password = 12XR5kbdmSxeeMqXm0V3
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect